version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PORT=5000
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped